name: polymer_app_router
description: Routing for polymer
version: 0.2.4
author: Walletek <hadrien.lejard@gmail.com>
homepage: https://github.com/walletek/polymer_app_router

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  analyzer: ">=0.27.0"
  polymer: ">=1.0.0-rc.14"
  route_hierarchical: "^0.6.2"
  dart_to_js_script_rewriter: "^0.1.0+4"
  web_components: "^0.12.0"
  browser: "^0.10.0"
  reflectable: ">=0.5.0"
  initialize: '>=0.6.0 <0.7.0'

transformers:
  - polymer:
      entry_points:
      - example/index.html
  - reflectable:
      entry_points:
      - example/main.dart
  - $dart2js:
      minify: false
      commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--enable-experimental-mirrors']
  - dart_to_js_script_rewriter